// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAs4bo3CLryAF-i9f8GunI5VvoNEDE-E',
    appId: '1:1003962949356:web:dffab17b341f60f474cfc9',
    messagingSenderId: '1003962949356',
    projectId: 'relmorg',
    authDomain: 'relmorg.firebaseapp.com',
    storageBucket: 'relmorg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDHxB5ZSHOaDMeQGAFG64NNizeDzsgl0',
    appId: '1:1003962949356:android:55b372cb682a021e74cfc9',
    messagingSenderId: '1003962949356',
    projectId: 'relmorg',
    storageBucket: 'relmorg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlDbvwdA38JsD-7L22XA-HAyNFBugBDY',
    appId: '1:1003962949356:ios:cffc65c26991108a74cfc9',
    messagingSenderId: '1003962949356',
    projectId: 'relmorg',
    storageBucket: 'relmorg.appspot.com',
    iosBundleId: 'com.example.relm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdlDbvwdA38JsD-7L22XA-HAyNFBugBDY',
    appId: '1:1003962949356:ios:35338cc4280dc28974cfc9',
    messagingSenderId: '1003962949356',
    projectId: 'relmorg',
    storageBucket: 'relmorg.appspot.com',
    iosBundleId: 'com.example.relm.RunnerTests',
  );
}
